services:
  keycloak:
    image: bitnami/keycloak:23.0.7
    container_name: genericlab-keycloak
    environment:
      # Admin credentials
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123

      # General Configuration
      KEYCLOAK_PRODUCTION: "false"

      # HTTP configuration
      KEYCLOAK_HTTP_PORT: 8080

    ports:
      - "8080:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data

    networks:
      - genericlab-network

  # Application Database
  postgres:
    image: postgres:15
    container_name: genericlab-db
    environment:
      POSTGRES_DB: genericlab
      POSTGRES_USER: genericlab
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - genericlab-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: genericlab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@genericlab.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - genericlab-network
    depends_on:
      - postgres

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local

networks:
  genericlab-network:
    driver: bridge
